## Numpy

In [1]:
#importing numpy with alias name np
import numpy as np

### Array creation and Properties

In [2]:
#creating arrays and reshaping it
arr1=np.arange(10)
arr2=np.arange(18)

In [3]:
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [4]:
#creating arrays and reshaping it
arr=np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
#metadata associated with the array
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(type(arr))

2
(5, 4)
20
int32
4
<class 'numpy.ndarray'>


In [6]:
help(arr)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [7]:
arr=np.array([1.0,12.0,13.0,14.0])
print(arr)
print(arr.dtype)
print(type(arr))

[ 1. 12. 13. 14.]
float64
<class 'numpy.ndarray'>


In [8]:
arr=np.eye(5)
dtype=np.float64
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
#linspace() and logspace
linarr=np.linspace(-15,20,18,endpoint=False)
print(linarr)

[-15.         -13.05555556 -11.11111111  -9.16666667  -7.22222222
  -5.27777778  -3.33333333  -1.38888889   0.55555556   2.5
   4.44444444   6.38888889   8.33333333  10.27777778  12.22222222
  14.16666667  16.11111111  18.05555556]


In [10]:
linarr=np.linspace(-15,20,18,endpoint=True)
print(linarr)

[-15.         -12.94117647 -10.88235294  -8.82352941  -6.76470588
  -4.70588235  -2.64705882  -0.58823529   1.47058824   3.52941176
   5.58823529   7.64705882   9.70588235  11.76470588  13.82352941
  15.88235294  17.94117647  20.        ]


In [11]:
logarr=np.logspace(-10,10,20,endpoint=True,base=10)
print(logarr)

[1.00000000e-10 1.12883789e-09 1.27427499e-08 1.43844989e-07
 1.62377674e-06 1.83298071e-05 2.06913808e-04 2.33572147e-03
 2.63665090e-02 2.97635144e-01 3.35981829e+00 3.79269019e+01
 4.28133240e+02 4.83293024e+03 5.45559478e+04 6.15848211e+05
 6.95192796e+06 7.84759970e+07 8.85866790e+08 1.00000000e+10]


In [12]:
logarr=np.logspace(-10,10,20,endpoint=False,base=10)
print(logarr)

[1.e-10 1.e-09 1.e-08 1.e-07 1.e-06 1.e-05 1.e-04 1.e-03 1.e-02 1.e-01
 1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09]


In [13]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [14]:
#initializing an array based on function
fun=np.fromfunction(lambda i,j:i==j,(3,3))
fun

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

### Array Operations

In [15]:
mat=np.arange(25).reshape(5,5)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
#scalar multiplication(on every element)
mat*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57],
       [60, 63, 66, 69, 72]])

In [17]:
#addition over two arrays is done to each corresponding index elements
mat+mat

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [18]:
#multiplication over two arrays is done on elements
mat*mat

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [19]:
#matrix multiplication using @
mat2=mat.transpose()
mat2

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [20]:
mat @ mat2

array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

In [21]:
mat @ mat

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

In [22]:
#sum on entire axes 
#row wise addition
print(mat)
mat.sum(axis=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([50, 55, 60, 65, 70])

In [23]:
#col wise addition
print(mat)
mat.sum(axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 10,  35,  60,  85, 110])

In [24]:
#um along entire array
mat.sum()

300

In [25]:
#extrema
print(mat.min(),mat.max())

0 24


### Universal functions

In [26]:
#new array scaled by pi
mat3=mat*np.pi/180
print(mat3)

[[0.         0.01745329 0.03490659 0.05235988 0.06981317]
 [0.08726646 0.10471976 0.12217305 0.13962634 0.15707963]
 [0.17453293 0.19198622 0.20943951 0.2268928  0.2443461 ]
 [0.26179939 0.27925268 0.29670597 0.31415927 0.33161256]
 [0.34906585 0.36651914 0.38397244 0.40142573 0.41887902]]


In [27]:
mat4=np.cos(mat3)

In [28]:
print(mat4)

[[1.         0.9998477  0.99939083 0.99862953 0.99756405]
 [0.9961947  0.9945219  0.99254615 0.99026807 0.98768834]
 [0.98480775 0.98162718 0.9781476  0.97437006 0.97029573]
 [0.96592583 0.9612617  0.95630476 0.95105652 0.94551858]
 [0.93969262 0.93358043 0.92718385 0.92050485 0.91354546]]


In [29]:
mat5=mat3+mat4

In [30]:
print(mat5)

[[1.         1.01730099 1.03429741 1.05098941 1.06737722]
 [1.08346116 1.09924165 1.1147192  1.12989441 1.14476797]
 [1.15934068 1.1736134  1.18758711 1.20126287 1.21464182]
 [1.22772521 1.24051438 1.25301073 1.26521578 1.27713113]
 [1.28875847 1.30009957 1.31115629 1.32193058 1.33242448]]


### Array slicing:accessing subarrays

In [31]:
#x[start:stop:step]

In [32]:
arr=np.arange(10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#accessing single ele
arr[5]

5

In [35]:
#accessing subarrays
arr[2:7]

array([2, 3, 4, 5, 6])

In [36]:
print(arr[2:4])

[2 3]


In [37]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Multidimensional arrays

In [38]:
arr=np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
arr[1,2]

6

In [40]:
arr[1:3,0:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
arr[:,2]

array([ 2,  6, 10, 14, 18])

In [42]:
arr[2:4,:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
#flattenning 
arr=arr.flatten()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [44]:
print(arr)
for row in arr:
    print(row)
arr=np.arange(20).reshape(5,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [45]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [46]:
for ele in arr.flat:
    print(ele)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [47]:
help(arr.flatten())

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

### copying arrays

In [48]:
arr1=np.arange(20)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [49]:
#no copy made
arr2=arr1
arr2 is arr1

True

In [50]:
#changes in shape of one reflects in the other
arr2.shape=(2,10)
print("arr2:")
print(arr2)
print(arr1.shape)
print("arr1:")
print(arr1)

arr2:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)
arr1:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [51]:
arr2 is arr1

True

In [52]:
#shallow coping
#changes on metadata doesn't reflect on the other
arr1=np.arange(20)
arr2=arr1[:]
arr1.shape=(4,5)
print(arr1)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
#but changes on data reflects data in the other,as underlying data is the same memory
arr2[6]=100
print(arr1)
print(arr2)

[[  0   1   2   3   4]
 [  5 100   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[  0   1   2   3   4   5 100   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [54]:
#slices are just the views pointing to the same mem
subarr=arr2[3:16]
print(subarr)

[  3   4   5 100   7   8   9  10  11  12  13  14  15]


In [55]:
subarr[:]=0

In [56]:
print(arr1)
print(arr2)
print(subarr)

[[ 0  1  2  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0 16 17 18 19]]
[ 0  1  2  0  0  0  0  0  0  0  0  0  0  0  0  0 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 0 0 0]


In [57]:
#different ways to check if two arrays are same,views or contain their own data
print(subarr is arr1)
print(subarr is arr2)
print(arr1 is arr2)
print(subarr.base is arr1)
print(subarr.flags.owndata)
print(arr1.flags.owndata)
print(arr2.flags.owndata)

False
False
False
True
False
True
False


In [58]:
#deep copying
coparr=arr1.copy()
coparr[:,:]=7
print(arr1)
print(coparr)

[[ 0  1  2  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0 16 17 18 19]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [59]:
coparr is arr1

False

In [60]:
coparr.base is arr1

False

### Boolean indexing

In [61]:
arr=np.arange(18).reshape(6,3)

In [62]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [63]:
#setting all ele >=9 to 100
arr[arr>=9]=100

In [64]:
arr

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [65]:
#setting all ele=100 to -10
arr[arr==100]=-10

In [66]:
arr

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [67]:
arr==-10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

``logical_or()`` ``logical_and()``

In [68]:
arr=np.arange(18).reshape(6,3)

In [69]:
arr[np.logical_and(arr>3,arr<=7)]=-3

In [70]:
arr

array([[ 0,  1,  2],
       [ 3, -3, -3],
       [-3, -3,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [71]:
#boolen array with same shape
arr>0

array([[False,  True,  True],
       [ True, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Avoiding loops

In [72]:
xmin=ymin=0.0
xmax=ymax=1.0
x=np.linspace(xmin,xmax,32,endpoint=True)
y=np.linspace(ymin,ymax,64,endpoint=True)
print(x.shape)
print(y.shape)
print(x)
print(y)

(32,)
(64,)
[0.         0.03225806 0.06451613 0.09677419 0.12903226 0.16129032
 0.19354839 0.22580645 0.25806452 0.29032258 0.32258065 0.35483871
 0.38709677 0.41935484 0.4516129  0.48387097 0.51612903 0.5483871
 0.58064516 0.61290323 0.64516129 0.67741935 0.70967742 0.74193548
 0.77419355 0.80645161 0.83870968 0.87096774 0.90322581 0.93548387
 0.96774194 1.        ]
[0.         0.01587302 0.03174603 0.04761905 0.06349206 0.07936508
 0.0952381  0.11111111 0.12698413 0.14285714 0.15873016 0.17460317
 0.19047619 0.20634921 0.22222222 0.23809524 0.25396825 0.26984127
 0.28571429 0.3015873  0.31746032 0.33333333 0.34920635 0.36507937
 0.38095238 0.3968254  0.41269841 0.42857143 0.44444444 0.46031746
 0.47619048 0.49206349 0.50793651 0.52380952 0.53968254 0.55555556
 0.57142857 0.58730159 0.6031746  0.61904762 0.63492063 0.65079365
 0.66666667 0.68253968 0.6984127  0.71428571 0.73015873 0.74603175
 0.76190476 0.77777778 0.79365079 0.80952381 0.82539683 0.84126984
 0.85714286 0.87301587 0.88

In [73]:
#time elapsed
import time
M=32
N=64
x=np.linspace(0.0,1.0,M,endpoint=False)
y=np.linspace(0.0,1.0,N,endpoint=False)

In [74]:
tic=time.time()
mat=np.zeros((M,N))
for i in range(M):
    for j in range(N):
        mat[i,j]=np.sin(2.0*np.pi*x[i]*y[i])
toc=time.time()
print("time elapsed:{} sec".format(toc-tic))
mat

time elapsed:0.01898360252380371 sec


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00306796, 0.00306796, 0.00306796, ..., 0.00306796, 0.00306796,
        0.00306796],
       [0.01227154, 0.01227154, 0.01227154, ..., 0.01227154, 0.01227154,
        0.01227154],
       ...,
       [0.53240313, 0.53240313, 0.53240313, ..., 0.53240313, 0.53240313,
        0.53240313],
       [0.37131719, 0.37131719, 0.37131719, ..., 0.37131719, 0.37131719,
        0.37131719],
       [0.1920804 , 0.1920804 , 0.1920804 , ..., 0.1920804 , 0.1920804 ,
        0.1920804 ]])

In [75]:
#extend 1d arrays to 2d
x2,y2=np.meshgrid(x,y,indexing='ij')
print(x2)
print(x2[:,0])
print(x2[0,:])

[[0.      0.      0.      ... 0.      0.      0.     ]
 [0.03125 0.03125 0.03125 ... 0.03125 0.03125 0.03125]
 [0.0625  0.0625  0.0625  ... 0.0625  0.0625  0.0625 ]
 ...
 [0.90625 0.90625 0.90625 ... 0.90625 0.90625 0.90625]
 [0.9375  0.9375  0.9375  ... 0.9375  0.9375  0.9375 ]
 [0.96875 0.96875 0.96875 ... 0.96875 0.96875 0.96875]]
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [76]:
#time elapsed using the above for the same operation(gets reduced)
print(mat)
tic=time.time()
mat=np.sin(2.0*np.pi*x2*y2)
mat
toc=time.time()
print("time elapsed:{} sec".format(toc-tic))

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.00306796 0.00306796 0.00306796 ... 0.00306796 0.00306796 0.00306796]
 [0.01227154 0.01227154 0.01227154 ... 0.01227154 0.01227154 0.01227154]
 ...
 [0.53240313 0.53240313 0.53240313 ... 0.53240313 0.53240313 0.53240313]
 [0.37131719 0.37131719 0.37131719 ... 0.37131719 0.37131719 0.37131719]
 [0.1920804  0.1920804  0.1920804  ... 0.1920804  0.1920804  0.1920804 ]]
time elapsed:0.0019474029541015625 sec


### Array concatenation and splitting

In [77]:
#concatenating 2 arrays
p=np.array([11,32,5,4,26,86])
q=np.array([74,49,58,60,52,21,67,96])
np.concatenate([q,p])

array([74, 49, 58, 60, 52, 21, 67, 96, 11, 32,  5,  4, 26, 86])

In [78]:
#concatenating more than 2 arrays
r=np.array([57,28,68,25,69,10])
np.concatenate([q,r,p])

array([74, 49, 58, 60, 52, 21, 67, 96, 57, 28, 68, 25, 69, 10, 11, 32,  5,
        4, 26, 86])

In [79]:
#for two-d arrays
m=np.array([[10,19,18],[20,29,28]])

In [80]:
#axis=0(row wise concatenation)
np.concatenate([m,m],axis=0)

array([[10, 19, 18],
       [20, 29, 28],
       [10, 19, 18],
       [20, 29, 28]])

In [81]:
#axis=1(col wise concatenation)
np.concatenate([m,m],axis=1)

array([[10, 19, 18, 10, 19, 18],
       [20, 29, 28, 20, 29, 28]])

### Splitting of arrays

``np.hsplit`` ``np.vsplit`` ``np.split``

In [82]:
chain=[1,2,3,4,1,2,3,4,6,5,43,8,7,6]
c1,c2,c3,c4=np.split(chain,[4,7,9])
print(c1,c2,c3,c4)

[1 2 3 4] [1 2 3] [4 6] [ 5 43  8  7  6]


In [83]:
child=np.arange(16).reshape((4,4))
child

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
mom,dad=np.hsplit(child,[2])
print(mom)
print(dad)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [85]:
mom,dad=np.vsplit(child,[2])
print(mom)
print(dad)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


### Aggregates

In [86]:
arr= np.arange(5,10)
print(arr)
np.add.reduce(arr)

[5 6 7 8 9]


35

In [87]:
np.multiply.reduce(arr)

15120

In [88]:
np.add.accumulate(arr)

array([ 5, 11, 18, 26, 35], dtype=int32)

In [89]:
np.multiply.accumulate(arr)

array([    5,    30,   210,  1680, 15120], dtype=int32)